apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy-mcp
  name: envoy-mcp
  namespace: kagent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: envoy-mcp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: envoy-mcp
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: mcp_envoy
          value: "true"
        image: chris530/envoy_mcp:10
        imagePullPolicy: Always
        name: envoymcp
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: envoy
      serviceAccountName: envoy
      terminationGracePeriodSeconds: 30
