apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy-mcp
  name: envoy-mcp
  namespace: kagent
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
  selector:
    app: envoy-mcp
